name: CI-CD
on: 
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - name: Obtendo o código
      uses: actions/checkout@v4.2.2
    - name: Autenticação no Docker Hub
      uses: docker/login-action@v3.4.0
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build da Imagem Docker
      uses: docker/build-push-action@v6.18.0
      with:
        context: ./src
        file: ./src/Dockerfile
        push: true
        tags: | 
          cleitonbarbosa/github-actions-pipeline:v${{ github.run_number }} 
          cleitonbarbosa/github-actions-pipeline:latest 
  
